# URL
root: /
permalink: :year/:month/:day/:title/

# Header
menu:
  Home: /

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
# code_dir: downloads/code
i18n_dir: :lang

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: /favicon.png

